name: blindkey_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.1+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

  # Cryptography & Security
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2

  # File & Storage
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  archive: ^3.6.1

  # Utilities
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  video_thumbnail: ^0.5.3
  intl: ^0.19.0
  uuid: ^4.5.1
  dartz: ^0.10.1
  video_player: ^2.10.1
  pdfrx: ^1.3.5
  open_file: ^3.3.2
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.0.0
  flutter_markdown: ^0.7.1
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  ntp: ^2.0.0
  excel: ^4.0.6
  xml: ^6.6.1
  shared_preferences: ^2.5.4
  youtube_player_flutter: ^9.1.3
  google_mobile_ads: ^5.1.0
  safe_device: ^1.3.8
  screen_protector: ^1.4.12
  flutter_tilt: 3.3.2
  auto_size_text: ^3.0.0
  app_links: ^6.4.1
  image: ^4.3.0
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/blindkey_logo.png"
  min_sdk_android: 21


flutter:


  uses-material-design: true


  assets:
    - assets/


